### ISSUE TITLE
Prefer  hashicorp/kubernetes over gavinbunney/kubectl provider

### ISSUE THREAD

**Issue by roni-frantchi** [env0/k8s-modules#4]
No good reason to use a 3rd party here.  
It is only ever used to create the `storage_class` and `csi_service_account` using yaml instead of HCL, but the equivalent HCL can be used in `hashicorp/kubernetes` or even yaml combined with `yamldecode()`.  

We could easily make the swap and drop this 3rd party dep.

**Comment by roni-frantchi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Close the 3 issues in env0/k8s-module](https://trello.com/c/oFSsnZRT/5332-close-the-3-issues-in-env0-k8s-module)

**Comment by roni-frantchi** [comment]
@yaronya can we close this issue?

**Comment by yaronya** [comment]
No not yet, See comment in #9:

> haven't removed the kubectl provider yet because customer use it and they need it to make the transition - otherwise kubectl resources would fail on destroy

**Comment by chpl** [comment]
There's no upgrade path to the new version of this module and we don't use `gavinbunney/kubectl ` in it.
